library:
  source-dirs: src
tests:
  hstu-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hstu
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- aeson
- http-conduit
- base >= 4.7 && < 5
name: hstu
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/hstu
license: BSD3
executables:
  hstu-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hstu
description: Please see the README on GitHub at <https://github.com/githubuser/hstu#readme>
